services:

  main_cloud:
    build:
      context: ./fast-api-tutorial2
      dockerfile: /Dockerfile
    image: dnn2:0.2
    command: >
      sh -c "nvidia-smi && python3 main_cloud.py --host 0.0.0.0 --port 8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    ports:
      - "8000:8000"

  test:
    build:
      context: ./fast-api-tutorial
      dockerfile: /Dockerfile
    image: dnn:0.1
    command: >
      sh -c "nvidia-smi && python3 main.py --host 0.0.0.0 --port 8088"
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    ports:
      - "8088:8088"
    depends_on:
      - main_cloud

